version: '3'

services:
  click-beard-api:
    build: .
    ports:
      - 3333:3333
    volumes:
      - api-data:/usr/api
    depends_on:
      - click-beard-postgres
  click-beard-postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=click-beard
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
  api-data: